language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-vertx' ]; then cd .. && eval "mv $currentfolder generator-vertx" && cd generator-vertx; fi

